// This file is auto-generated by alef. DO NOT EDIT.
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzberg;

namespace Kreuzberg.E2e;

/// <summary>E2e tests for category: embeddings.</summary>
public class EmbeddingsTests
{
    private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

    [Fact]
    public async Task Test_EmbeddingDisabled()
    {
        // Tests chunking without embeddings - chunks should not have embedding vectors
        var result = await Kreuzberg.ExtractFile("", null, null);
        Assert.Equal("application/pdf", result.MimeType.Trim());
        Assert.True(result.Content.Length >= 10, "expected length >= 10");
        Assert.True(result.Chunks.Count >= 1, "expected at least 1 elements");
        // TODO: unsupported assertion type: is_true
    }
}
