// This file is auto-generated by alef. DO NOT EDIT.
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzberg;

namespace Kreuzberg.E2e;

/// <summary>E2e tests for category: pdf.</summary>
public class PdfTests
{
    private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

    [Fact]
    public async Task Test_PdfAssemblyTechnical()
    {
        // Assembly language technical manual with large body of text.
        var result = await Kreuzberg.ExtractFile("", null, null);
        Assert.Equal("application/pdf", result.MimeType.Trim());
        Assert.True(result.Content.Length >= 5000, "expected length >= 5000");
        Assert.True(result.Content.ToString().Contains("assembly") || result.Content.ToString().Contains("register") || result.Content.ToString().Contains("instruction"), "expected to contain at least one of the specified values");
        Assert.Equal("pdf", result.Metadata.FormatType.Trim());
    }

    [Fact]
    public async Task Test_PdfBayesianDataAnalysis()
    {
        // Bayesian data analysis textbook PDF with large content volume.
        var result = await Kreuzberg.ExtractFile("", null, null);
        Assert.Equal("application/pdf", result.MimeType.Trim());
        Assert.True(result.Content.Length >= 10000, "expected length >= 10000");
        Assert.True(result.Content.ToString().Contains("Bayesian") || result.Content.ToString().Contains("probability") || result.Content.ToString().Contains("distribution"), "expected to contain at least one of the specified values");
        Assert.Equal("pdf", result.Metadata.FormatType.Trim());
    }

    [Fact]
    public async Task Test_PdfCodeAndFormula()
    {
        // PDF containing code snippets and formulas should retain substantial content.
        var result = await Kreuzberg.ExtractFile("", null, null);
        Assert.Equal("application/pdf", result.MimeType.Trim());
        Assert.True(result.Content.Length >= 100, "expected length >= 100");
    }

    [Fact]
    public async Task Test_PdfDeepLearning()
    {
        // Deep learning textbook PDF to ensure long-form extraction quality.
        var result = await Kreuzberg.ExtractFile("", null, null);
        Assert.Equal("application/pdf", result.MimeType.Trim());
        Assert.True(result.Content.Length >= 1000, "expected length >= 1000");
        Assert.True(result.Content.ToString().Contains("neural") || result.Content.ToString().Contains("network") || result.Content.ToString().Contains("deep learning"), "expected to contain at least one of the specified values");
        Assert.Equal("pdf", result.Metadata.FormatType.Trim());
    }

    [Fact]
    public async Task Test_PdfEmbeddedImages()
    {
        // PDF with embedded images should extract text and tables when present.
        var result = await Kreuzberg.ExtractFile("", null, null);
        Assert.Equal("application/pdf", result.MimeType.Trim());
        Assert.True(result.Content.Length >= 50, "expected length >= 50");
        Assert.True(result.Tables.Count >= 0, "expected at least 0 elements");
    }

    [Fact]
    public async Task Test_PdfGoogleDoc()
    {
        // Google Docs exported PDF to verify conversion fidelity.
        var result = await Kreuzberg.ExtractFile("", null, null);
        Assert.Equal("application/pdf", result.MimeType.Trim());
        Assert.True(result.Content.Length >= 50, "expected length >= 50");
        Assert.Equal("pdf", result.Metadata.FormatType.Trim());
    }

    [Fact]
    public async Task Test_PdfLargeCiml()
    {
        // Large machine learning textbook PDF to stress extraction length.
        var result = await Kreuzberg.ExtractFile("", null, null);
        Assert.Equal("application/pdf", result.MimeType.Trim());
        Assert.True(result.Content.Length >= 10000, "expected length >= 10000");
        Assert.True(result.Content.ToString().Contains("machine learning") || result.Content.ToString().Contains("algorithm") || result.Content.ToString().Contains("training"), "expected to contain at least one of the specified values");
        Assert.Equal("pdf", result.Metadata.FormatType.Trim());
    }

    [Fact]
    public async Task Test_PdfNonEnglishGerman()
    {
        // German technical PDF to ensure non-ASCII content extraction.
        var result = await Kreuzberg.ExtractFile("", null, null);
        Assert.Equal("application/pdf", result.MimeType.Trim());
        Assert.True(result.Content.Length >= 100, "expected length >= 100");
        Assert.True(result.Content.ToString().Contains("Intel") || result.Content.ToString().Contains("paging"), "expected to contain at least one of the specified values");
        Assert.Equal("pdf", result.Metadata.FormatType.Trim());
    }

    [Fact]
    public async Task Test_PdfRightToLeft()
    {
        // Right-to-left language PDF to verify RTL extraction.
        var result = await Kreuzberg.ExtractFile("", null, null);
        Assert.Equal("application/pdf", result.MimeType.Trim());
        Assert.True(result.Content.Length >= 50, "expected length >= 50");
        Assert.Equal("pdf", result.Metadata.FormatType.Trim());
    }

    [Fact]
    public async Task Test_PdfSimpleText()
    {
        // Simple text-heavy PDF should extract content without OCR or tables.
        var result = await Kreuzberg.ExtractFile("", null, null);
        Assert.Equal("application/pdf", result.MimeType.Trim());
        Assert.True(result.Content.Length >= 50, "expected length >= 50");
        Assert.True(result.Content.ToString().Contains("May 5, 2023") || result.Content.ToString().Contains("To Whom it May Concern") || result.Content.ToString().Contains("Mallori"), "expected to contain at least one of the specified values");
    }

    [Fact]
    public async Task Test_PdfTablesLarge()
    {
        // Large PDF with extensive tables to stress table extraction.
        var result = await Kreuzberg.ExtractFile("", null, null);
        Assert.Equal("application/pdf", result.MimeType.Trim());
        Assert.True(result.Content.Length >= 500, "expected length >= 500");
    }

    [Fact]
    public async Task Test_PdfTablesMedium()
    {
        // Medium-sized PDF with multiple tables.
        var result = await Kreuzberg.ExtractFile("", null, null);
        Assert.Equal("application/pdf", result.MimeType.Trim());
        Assert.True(result.Content.Length >= 100, "expected length >= 100");
    }

    [Fact]
    public async Task Test_PdfTechnicalStatLearning()
    {
        // Technical statistical learning PDF requiring substantial extraction.
        var result = await Kreuzberg.ExtractFile("", null, null);
        Assert.Equal("application/pdf", result.MimeType.Trim());
        Assert.True(result.Content.Length >= 10000, "expected length >= 10000");
        Assert.True(result.Content.ToString().Contains("statistical") || result.Content.ToString().Contains("regression") || result.Content.ToString().Contains("learning"), "expected to contain at least one of the specified values");
        Assert.Equal("pdf", result.Metadata.FormatType.Trim());
    }
}
