// This file is auto-generated by alef. DO NOT EDIT.
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzberg;

namespace Kreuzberg.E2e;

/// <summary>E2e tests for category: render.</summary>
public class RenderTests
{
    private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

    [Fact]
    public async Task Test_RenderCustomDpi()
    {
        // Render PDF page with custom DPI
        var result = await Kreuzberg.ExtractFile("", null, null);
        // TODO: unsupported assertion type: is_true
        Assert.True(result.ByteLength >= 50, "expected >= 50");
    }

    [Fact]
    public async Task Test_RenderIterator()
    {
        // Iterate all PDF pages as PNG images
        var result = await Kreuzberg.ExtractFile("", null, null);
        // TODO: unsupported assertion type: is_true
        Assert.True(result.PageCount >= 1, "expected >= 1");
    }

    [Fact]
    public async Task Test_RenderSinglePage()
    {
        // Render a single PDF page to PNG
        var result = await Kreuzberg.ExtractFile("", null, null);
        // TODO: unsupported assertion type: is_true
        Assert.True(result.ByteLength >= 100, "expected >= 100");
    }
}
