// This file is auto-generated by alef. DO NOT EDIT.
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzberg;

namespace Kreuzberg.E2e;

/// <summary>E2e tests for category: token_reduction.</summary>
public class TokenReductionTests
{
    private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

    [Fact]
    public async Task Test_TokenReductionAggressive()
    {
        // Tests aggressive token reduction mode significantly reduces content
        var result = await Kreuzberg.ExtractFile("", null, null);
        Assert.Equal("application/pdf", result.MimeType.Trim());
        Assert.True(result.Content.Length >= 5, "expected length >= 5");
        Assert.True(result.Content.Length <= 150, "expected length <= 150");
        Assert.False(string.IsNullOrEmpty(result.Content?.ToString()));
    }

    [Fact]
    public async Task Test_TokenReductionBasic()
    {
        // Tests basic token reduction on PDF document
        var result = await Kreuzberg.ExtractFile("", null, null);
        Assert.Equal("application/pdf", result.MimeType.Trim());
        Assert.True(result.Content.Length >= 5, "expected length >= 5");
        Assert.True(result.Content.Length <= 200, "expected length <= 200");
        Assert.False(string.IsNullOrEmpty(result.Content?.ToString()));
    }

    [Fact]
    public async Task Test_TokenReductionLight()
    {
        // Tests light token reduction mode preserves most content
        var result = await Kreuzberg.ExtractFile("", null, null);
        Assert.Equal("application/pdf", result.MimeType.Trim());
        Assert.True(result.Content.Length >= 10, "expected length >= 10");
        Assert.False(string.IsNullOrEmpty(result.Content?.ToString()));
    }

    [Fact]
    public async Task Test_TokenReductionWithChunking()
    {
        // Tests token reduction combined with chunking
        var result = await Kreuzberg.ExtractFile("", null, null);
        Assert.Equal("application/pdf", result.MimeType.Trim());
        Assert.True(result.Content.Length >= 5, "expected length >= 5");
        Assert.True(result.Content.Length <= 200, "expected length <= 200");
        Assert.False(string.IsNullOrEmpty(result.Content?.ToString()));
        Assert.True(result.Chunks.Count >= 1, "expected at least 1 elements");
        // TODO: unsupported assertion type: is_true
    }
}
