<?php
// This file is auto-generated by alef. DO NOT EDIT.

declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg\Kreuzberg;

/** E2e tests for category: document_extractor_management. */
final class DocumentExtractorManagementTest extends TestCase
{
    /** Clear all document extractors and verify list is empty */
    public function test_extractors_clear(): void
    {
        $result = Kreuzberg\Kreuzberg::extractFile("");
        $this->assertEmpty($result->result);
    }

    /** List all registered document extractors */
    public function test_extractors_list(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg\Kreuzberg::extractFile("");
    }

    /** Unregister nonexistent document extractor gracefully */
    public function test_extractors_unregister(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg\Kreuzberg::extractFile("");
    }
}
