<?php
// This file is auto-generated by alef. DO NOT EDIT.

declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg\Kreuzberg;

/** E2e tests for category: embeddings. */
final class EmbeddingsTest extends TestCase
{
    /** Tests chunking without embeddings - chunks should not have embedding vectors */
    public function test_embedding_disabled(): void
    {
        $result = Kreuzberg\Kreuzberg::extractFile("");
        $this->assertEquals("application/pdf", $result->mime_type);
        $this->assertGreaterThanOrEqual(10, strlen($result->content));
        $this->assertGreaterThanOrEqual(1, count($result->chunks));
        // TODO: unsupported assertion type: is_true
    }
}
