<?php
// This file is auto-generated by alef. DO NOT EDIT.

declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg\Kreuzberg;

/** E2e tests for category: mime_utilities. */
final class MimeUtilitiesTest extends TestCase
{
    /** Detect MIME type from file bytes */
    public function test_mime_detect_bytes(): void
    {
        $result = Kreuzberg\Kreuzberg::extractFile("");
        $this->assertStringContainsString("pdf", $result->result);
    }

    /** Detect MIME type from file path */
    public function test_mime_detect_path(): void
    {
        $result = Kreuzberg\Kreuzberg::extractFile("");
        $this->assertStringContainsString("text", $result->result);
    }

    /** Get file extensions for a MIME type */
    public function test_mime_get_extensions(): void
    {
        $result = Kreuzberg\Kreuzberg::extractFile("");
        $this->assertStringContainsString("pdf", $result->result);
    }
}
