<?php
// This file is auto-generated by alef. DO NOT EDIT.

declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg\Kreuzberg;

/** E2e tests for category: pdf. */
final class PdfTest extends TestCase
{
    /** Assembly language technical manual with large body of text. */
    public function test_pdf_assembly_technical(): void
    {
        $result = Kreuzberg\Kreuzberg::extractFile("");
        $this->assertEquals("application/pdf", $result->mime_type);
        $this->assertGreaterThanOrEqual(5000, strlen($result->content));
        $found = false;
        if (str_contains($result->content, "assembly")) { $found = true; }
        if (str_contains($result->content, "register")) { $found = true; }
        if (str_contains($result->content, "instruction")) { $found = true; }
        $this->assertTrue($found, 'expected to contain at least one of the specified values');
        $this->assertEquals("pdf", $result->metadata->format_type);
    }

    /** Bayesian data analysis textbook PDF with large content volume. */
    public function test_pdf_bayesian_data_analysis(): void
    {
        $result = Kreuzberg\Kreuzberg::extractFile("");
        $this->assertEquals("application/pdf", $result->mime_type);
        $this->assertGreaterThanOrEqual(10000, strlen($result->content));
        $found = false;
        if (str_contains($result->content, "Bayesian")) { $found = true; }
        if (str_contains($result->content, "probability")) { $found = true; }
        if (str_contains($result->content, "distribution")) { $found = true; }
        $this->assertTrue($found, 'expected to contain at least one of the specified values');
        $this->assertEquals("pdf", $result->metadata->format_type);
    }

    /** PDF containing code snippets and formulas should retain substantial content. */
    public function test_pdf_code_and_formula(): void
    {
        $result = Kreuzberg\Kreuzberg::extractFile("");
        $this->assertEquals("application/pdf", $result->mime_type);
        $this->assertGreaterThanOrEqual(100, strlen($result->content));
    }

    /** Deep learning textbook PDF to ensure long-form extraction quality. */
    public function test_pdf_deep_learning(): void
    {
        $result = Kreuzberg\Kreuzberg::extractFile("");
        $this->assertEquals("application/pdf", $result->mime_type);
        $this->assertGreaterThanOrEqual(1000, strlen($result->content));
        $found = false;
        if (str_contains($result->content, "neural")) { $found = true; }
        if (str_contains($result->content, "network")) { $found = true; }
        if (str_contains($result->content, "deep learning")) { $found = true; }
        $this->assertTrue($found, 'expected to contain at least one of the specified values');
        $this->assertEquals("pdf", $result->metadata->format_type);
    }

    /** PDF with embedded images should extract text and tables when present. */
    public function test_pdf_embedded_images(): void
    {
        $result = Kreuzberg\Kreuzberg::extractFile("");
        $this->assertEquals("application/pdf", $result->mime_type);
        $this->assertGreaterThanOrEqual(50, strlen($result->content));
        $this->assertGreaterThanOrEqual(0, count($result->tables));
    }

    /** Google Docs exported PDF to verify conversion fidelity. */
    public function test_pdf_google_doc(): void
    {
        $result = Kreuzberg\Kreuzberg::extractFile("");
        $this->assertEquals("application/pdf", $result->mime_type);
        $this->assertGreaterThanOrEqual(50, strlen($result->content));
        $this->assertEquals("pdf", $result->metadata->format_type);
    }

    /** Large machine learning textbook PDF to stress extraction length. */
    public function test_pdf_large_ciml(): void
    {
        $result = Kreuzberg\Kreuzberg::extractFile("");
        $this->assertEquals("application/pdf", $result->mime_type);
        $this->assertGreaterThanOrEqual(10000, strlen($result->content));
        $found = false;
        if (str_contains($result->content, "machine learning")) { $found = true; }
        if (str_contains($result->content, "algorithm")) { $found = true; }
        if (str_contains($result->content, "training")) { $found = true; }
        $this->assertTrue($found, 'expected to contain at least one of the specified values');
        $this->assertEquals("pdf", $result->metadata->format_type);
    }

    /** German technical PDF to ensure non-ASCII content extraction. */
    public function test_pdf_non_english_german(): void
    {
        $result = Kreuzberg\Kreuzberg::extractFile("");
        $this->assertEquals("application/pdf", $result->mime_type);
        $this->assertGreaterThanOrEqual(100, strlen($result->content));
        $found = false;
        if (str_contains($result->content, "Intel")) { $found = true; }
        if (str_contains($result->content, "paging")) { $found = true; }
        $this->assertTrue($found, 'expected to contain at least one of the specified values');
        $this->assertEquals("pdf", $result->metadata->format_type);
    }

    /** Right-to-left language PDF to verify RTL extraction. */
    public function test_pdf_right_to_left(): void
    {
        $result = Kreuzberg\Kreuzberg::extractFile("");
        $this->assertEquals("application/pdf", $result->mime_type);
        $this->assertGreaterThanOrEqual(50, strlen($result->content));
        $this->assertEquals("pdf", $result->metadata->format_type);
    }

    /** Simple text-heavy PDF should extract content without OCR or tables. */
    public function test_pdf_simple_text(): void
    {
        $result = Kreuzberg\Kreuzberg::extractFile("");
        $this->assertEquals("application/pdf", $result->mime_type);
        $this->assertGreaterThanOrEqual(50, strlen($result->content));
        $found = false;
        if (str_contains($result->content, "May 5, 2023")) { $found = true; }
        if (str_contains($result->content, "To Whom it May Concern")) { $found = true; }
        if (str_contains($result->content, "Mallori")) { $found = true; }
        $this->assertTrue($found, 'expected to contain at least one of the specified values');
    }

    /** Large PDF with extensive tables to stress table extraction. */
    public function test_pdf_tables_large(): void
    {
        $result = Kreuzberg\Kreuzberg::extractFile("");
        $this->assertEquals("application/pdf", $result->mime_type);
        $this->assertGreaterThanOrEqual(500, strlen($result->content));
    }

    /** Medium-sized PDF with multiple tables. */
    public function test_pdf_tables_medium(): void
    {
        $result = Kreuzberg\Kreuzberg::extractFile("");
        $this->assertEquals("application/pdf", $result->mime_type);
        $this->assertGreaterThanOrEqual(100, strlen($result->content));
    }

    /** Technical statistical learning PDF requiring substantial extraction. */
    public function test_pdf_technical_stat_learning(): void
    {
        $result = Kreuzberg\Kreuzberg::extractFile("");
        $this->assertEquals("application/pdf", $result->mime_type);
        $this->assertGreaterThanOrEqual(10000, strlen($result->content));
        $found = false;
        if (str_contains($result->content, "statistical")) { $found = true; }
        if (str_contains($result->content, "regression")) { $found = true; }
        if (str_contains($result->content, "learning")) { $found = true; }
        $this->assertTrue($found, 'expected to contain at least one of the specified values');
        $this->assertEquals("pdf", $result->metadata->format_type);
    }
}
