<?php
// This file is auto-generated by alef. DO NOT EDIT.

declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg\Kreuzberg;

/** E2e tests for category: render. */
final class RenderTest extends TestCase
{
    /** Render PDF page with custom DPI */
    public function test_render_custom_dpi(): void
    {
        $result = Kreuzberg\Kreuzberg::extractFile("");
        // TODO: unsupported assertion type: is_true
        $this->assertGreaterThanOrEqual(50, $result->byte_length);
    }

    /** Iterate all PDF pages as PNG images */
    public function test_render_iterator(): void
    {
        $result = Kreuzberg\Kreuzberg::extractFile("");
        // TODO: unsupported assertion type: is_true
        $this->assertGreaterThanOrEqual(1, $result->page_count);
    }

    /** Render a single PDF page to PNG */
    public function test_render_single_page(): void
    {
        $result = Kreuzberg\Kreuzberg::extractFile("");
        // TODO: unsupported assertion type: is_true
        $this->assertGreaterThanOrEqual(100, $result->byte_length);
    }
}
