<?php
// This file is auto-generated by alef. DO NOT EDIT.

declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg\Kreuzberg;

/** E2e tests for category: token_reduction. */
final class TokenReductionTest extends TestCase
{
    /** Tests aggressive token reduction mode significantly reduces content */
    public function test_token_reduction_aggressive(): void
    {
        $result = Kreuzberg\Kreuzberg::extractFile("");
        $this->assertEquals("application/pdf", $result->mime_type);
        $this->assertGreaterThanOrEqual(5, strlen($result->content));
        $this->assertLessThanOrEqual(150, strlen($result->content));
        $this->assertNotEmpty($result->content);
    }

    /** Tests basic token reduction on PDF document */
    public function test_token_reduction_basic(): void
    {
        $result = Kreuzberg\Kreuzberg::extractFile("");
        $this->assertEquals("application/pdf", $result->mime_type);
        $this->assertGreaterThanOrEqual(5, strlen($result->content));
        $this->assertLessThanOrEqual(200, strlen($result->content));
        $this->assertNotEmpty($result->content);
    }

    /** Tests light token reduction mode preserves most content */
    public function test_token_reduction_light(): void
    {
        $result = Kreuzberg\Kreuzberg::extractFile("");
        $this->assertEquals("application/pdf", $result->mime_type);
        $this->assertGreaterThanOrEqual(10, strlen($result->content));
        $this->assertNotEmpty($result->content);
    }

    /** Tests token reduction combined with chunking */
    public function test_token_reduction_with_chunking(): void
    {
        $result = Kreuzberg\Kreuzberg::extractFile("");
        $this->assertEquals("application/pdf", $result->mime_type);
        $this->assertGreaterThanOrEqual(5, strlen($result->content));
        $this->assertLessThanOrEqual(200, strlen($result->content));
        $this->assertNotEmpty($result->content);
        $this->assertGreaterThanOrEqual(1, count($result->chunks));
        // TODO: unsupported assertion type: is_true
    }
}
