// This file is auto-generated by alef. DO NOT EDIT.
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Type of text chunker to use.
///
/// # Variants
///
/// * `Text` - Generic text splitter, splits on whitespace and punctuation
/// * `Markdown` - Markdown-aware splitter, preserves formatting and structure
/// * `Yaml` - YAML-aware splitter, creates one chunk per top-level key
/// * `Semantic` - Topic-aware chunker that splits at natural document boundaries
///   (headers, paragraph breaks, topic shifts). Works out of the box with no extra
///   configuration. Optionally add an `EmbeddingConfig` for embedding-based topic
///   detection; `topic_threshold` (default 0.75) and `max_characters` (default 1000)
///   are automatically applied when not specified.
/// </summary>
public enum ChunkerType
{
    [JsonPropertyName("text")]
    Text,
    [JsonPropertyName("markdown")]
    Markdown,
    [JsonPropertyName("yaml")]
    Yaml,
    [JsonPropertyName("semantic")]
    Semantic,
}
