// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

public class CancelledException extends KreuzbergErrorException {
    public CancelledException(String message) {
        super(message);
    }

    public CancelledException(String message, Throwable cause) {
        super(message, cause);
    }
}
