// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;

public record DetectedBoundary(
    @JsonProperty("byte_offset") long byteOffset,
    @JsonProperty("is_header") boolean isHeader
) {
}
