// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;


public class LayoutRegionBuilder {

    private String class = "";
    private double confidence = 0.0;
    private String boundingBox = "";
    private double areaFraction = 0.0;

    public LayoutRegionBuilder withClass(String value) {
        this.class = value;
        return this;
    }

    public LayoutRegionBuilder withConfidence(double value) {
        this.confidence = value;
        return this;
    }

    public LayoutRegionBuilder withBoundingBox(String value) {
        this.boundingBox = value;
        return this;
    }

    public LayoutRegionBuilder withAreaFraction(double value) {
        this.areaFraction = value;
        return this;
    }

    public LayoutRegion build() {
        return new LayoutRegion(
            class,
            confidence,
            boundingBox,
            areaFraction
        );
    }
}
