// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;

public record LayoutRegion(
    String class,
    double confidence,
    @JsonProperty("bounding_box") String boundingBox,
    @JsonProperty("area_fraction") double areaFraction
) {
    public static LayoutRegionBuilder builder() {
        return new LayoutRegionBuilder();
    }
}
