// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import java.util.Optional;

public class LayoutDetectionConfigBuilder {

    private Optional<Float> confidenceThreshold = Optional.empty();
    private boolean applyHeuristics = false;
    private TableModel tableModel = null;
    private Optional<AccelerationConfig> acceleration = Optional.empty();

    public LayoutDetectionConfigBuilder withConfidenceThreshold(Optional<Float> value) {
        this.confidenceThreshold = value;
        return this;
    }

    public LayoutDetectionConfigBuilder withApplyHeuristics(boolean value) {
        this.applyHeuristics = value;
        return this;
    }

    public LayoutDetectionConfigBuilder withTableModel(TableModel value) {
        this.tableModel = value;
        return this;
    }

    public LayoutDetectionConfigBuilder withAcceleration(Optional<AccelerationConfig> value) {
        this.acceleration = value;
        return this;
    }

    public LayoutDetectionConfig build() {
        return new LayoutDetectionConfig(
            confidenceThreshold,
            applyHeuristics,
            tableModel,
            acceleration
        );
    }
}
