// DO NOT EDIT - auto-generated by alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;

public record MergedChunk(
    String text,
    @JsonProperty("byte_start") long byteStart,
    @JsonProperty("byte_end") long byteEnd
) {
}
