# This file is auto-generated by alef. DO NOT EDIT.
# E2e tests for category: pdf

test_that("pdf_assembly_technical: Assembly language technical manual with large body of text.", {
  result <- extract_file()
  expect_equal(trimws(result$mime_type), "application/pdf")
  expect_true(nchar(result$content) >= 5000)
  expect_true(any(sapply(c("assembly", "register", "instruction"), function(v) grepl(v, result$content, fixed = TRUE))))
  expect_equal(trimws(result$metadata$format_type), "pdf")
})

test_that("pdf_bayesian_data_analysis: Bayesian data analysis textbook PDF with large content volume.", {
  result <- extract_file()
  expect_equal(trimws(result$mime_type), "application/pdf")
  expect_true(nchar(result$content) >= 10000)
  expect_true(any(sapply(c("Bayesian", "probability", "distribution"), function(v) grepl(v, result$content, fixed = TRUE))))
  expect_equal(trimws(result$metadata$format_type), "pdf")
})

test_that("pdf_code_and_formula: PDF containing code snippets and formulas should retain substantial content.", {
  result <- extract_file()
  expect_equal(trimws(result$mime_type), "application/pdf")
  expect_true(nchar(result$content) >= 100)
})

test_that("pdf_deep_learning: Deep learning textbook PDF to ensure long-form extraction quality.", {
  result <- extract_file()
  expect_equal(trimws(result$mime_type), "application/pdf")
  expect_true(nchar(result$content) >= 1000)
  expect_true(any(sapply(c("neural", "network", "deep learning"), function(v) grepl(v, result$content, fixed = TRUE))))
  expect_equal(trimws(result$metadata$format_type), "pdf")
})

test_that("pdf_embedded_images: PDF with embedded images should extract text and tables when present.", {
  result <- extract_file()
  expect_equal(trimws(result$mime_type), "application/pdf")
  expect_true(nchar(result$content) >= 50)
  expect_true(length(result$tables) >= 0)
})

test_that("pdf_google_doc: Google Docs exported PDF to verify conversion fidelity.", {
  result <- extract_file()
  expect_equal(trimws(result$mime_type), "application/pdf")
  expect_true(nchar(result$content) >= 50)
  expect_equal(trimws(result$metadata$format_type), "pdf")
})

test_that("pdf_large_ciml: Large machine learning textbook PDF to stress extraction length.", {
  result <- extract_file()
  expect_equal(trimws(result$mime_type), "application/pdf")
  expect_true(nchar(result$content) >= 10000)
  expect_true(any(sapply(c("machine learning", "algorithm", "training"), function(v) grepl(v, result$content, fixed = TRUE))))
  expect_equal(trimws(result$metadata$format_type), "pdf")
})

test_that("pdf_non_english_german: German technical PDF to ensure non-ASCII content extraction.", {
  result <- extract_file()
  expect_equal(trimws(result$mime_type), "application/pdf")
  expect_true(nchar(result$content) >= 100)
  expect_true(any(sapply(c("Intel", "paging"), function(v) grepl(v, result$content, fixed = TRUE))))
  expect_equal(trimws(result$metadata$format_type), "pdf")
})

test_that("pdf_right_to_left: Right-to-left language PDF to verify RTL extraction.", {
  result <- extract_file()
  expect_equal(trimws(result$mime_type), "application/pdf")
  expect_true(nchar(result$content) >= 50)
  expect_equal(trimws(result$metadata$format_type), "pdf")
})

test_that("pdf_simple_text: Simple text-heavy PDF should extract content without OCR or tables.", {
  result <- extract_file()
  expect_equal(trimws(result$mime_type), "application/pdf")
  expect_true(nchar(result$content) >= 50)
  expect_true(any(sapply(c("May 5, 2023", "To Whom it May Concern", "Mallori"), function(v) grepl(v, result$content, fixed = TRUE))))
})

test_that("pdf_tables_large: Large PDF with extensive tables to stress table extraction.", {
  result <- extract_file()
  expect_equal(trimws(result$mime_type), "application/pdf")
  expect_true(nchar(result$content) >= 500)
})

test_that("pdf_tables_medium: Medium-sized PDF with multiple tables.", {
  result <- extract_file()
  expect_equal(trimws(result$mime_type), "application/pdf")
  expect_true(nchar(result$content) >= 100)
})

test_that("pdf_technical_stat_learning: Technical statistical learning PDF requiring substantial extraction.", {
  result <- extract_file()
  expect_equal(trimws(result$mime_type), "application/pdf")
  expect_true(nchar(result$content) >= 10000)
  expect_true(any(sapply(c("statistical", "regression", "learning"), function(v) grepl(v, result$content, fixed = TRUE))))
  expect_equal(trimws(result$metadata$format_type), "pdf")
})
