# This file is auto-generated by alef. DO NOT EDIT.
# E2e tests for category: token_reduction

test_that("token_reduction_aggressive: Tests aggressive token reduction mode significantly reduces content", {
  result <- extract_file()
  expect_equal(trimws(result$mime_type), "application/pdf")
  expect_true(nchar(result$content) >= 5)
  expect_true(nchar(result$content) <= 150)
  expect_true(if (is.character(result$content)) nchar(result$content) > 0 else length(result$content) > 0)
})

test_that("token_reduction_basic: Tests basic token reduction on PDF document", {
  result <- extract_file()
  expect_equal(trimws(result$mime_type), "application/pdf")
  expect_true(nchar(result$content) >= 5)
  expect_true(nchar(result$content) <= 200)
  expect_true(if (is.character(result$content)) nchar(result$content) > 0 else length(result$content) > 0)
})

test_that("token_reduction_light: Tests light token reduction mode preserves most content", {
  result <- extract_file()
  expect_equal(trimws(result$mime_type), "application/pdf")
  expect_true(nchar(result$content) >= 10)
  expect_true(if (is.character(result$content)) nchar(result$content) > 0 else length(result$content) > 0)
})

test_that("token_reduction_with_chunking: Tests token reduction combined with chunking", {
  result <- extract_file()
  expect_equal(trimws(result$mime_type), "application/pdf")
  expect_true(nchar(result$content) >= 5)
  expect_true(nchar(result$content) <= 200)
  expect_true(if (is.character(result$content)) nchar(result$content) > 0 else length(result$content) > 0)
  expect_true(length(result$chunks) >= 1)
  # TODO: unsupported assertion type: is_true
})
