# This file is auto-generated by alef. DO NOT EDIT.
# E2e tests for category: render

test_that("render_custom_dpi: Render PDF page with custom DPI", {
  result <- extract_file()
  # TODO: unsupported assertion type: is_true
  expect_true(result$byte_length >= 50)
})

test_that("render_iterator: Iterate all PDF pages as PNG images", {
  result <- extract_file()
  # TODO: unsupported assertion type: is_true
  expect_true(result$page_count >= 1)
})

test_that("render_single_page: Render a single PDF page to PNG", {
  result <- extract_file()
  # TODO: unsupported assertion type: is_true
  expect_true(result$byte_length >= 100)
})
