# This file is auto-generated by alef. DO NOT EDIT.
# E2e tests for category: embeddings

test_that("embedding_disabled: Tests chunking without embeddings - chunks should not have embedding vectors", {
  result <- extract_file()
  expect_equal(trimws(result$mime_type), "application/pdf")
  expect_true(nchar(result$content) >= 10)
  expect_true(length(result$chunks) >= 1)
  # TODO: unsupported assertion type: is_true
})
