// This file is auto-generated by alef. DO NOT EDIT.
package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.Kreuzberg;

/** E2e tests for category: embeddings. */
class EmbeddingsTest {
    @Test
    void testEmbeddingDisabled() throws Exception {
        // Tests chunking without embeddings - chunks should not have embedding vectors
        var result = Kreuzberg.extractFile("");
        assertEquals("application/pdf", result.mimeType().trim());
        assertTrue(result.content().orElse("").length() >= 10, "expected length >= 10");
        assertTrue(result.chunks().size() >= 1, "expected at least 1 elements");
        // TODO: unsupported assertion type: is_true
    }

}
