// This file is auto-generated by alef. DO NOT EDIT.
package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.Kreuzberg;

/** E2e tests for category: image. */
class ImageTest {
    @Test
    void testImageMetadataOnly() throws Exception {
        // JPEG image to validate metadata extraction without OCR.
        var result = Kreuzberg.extractFile("");
        assertEquals("image/jpeg", result.mimeType().trim());
        assertTrue(result.content().orElse("").length() <= 200, "expected length <= 200");
    }

    @Test
    void testImageSvgBasic() throws Exception {
        // SVG image extraction.
        var result = Kreuzberg.extractFile("");
        assertEquals("image/svg+xml", result.mimeType().trim());
        assertTrue(result.content().orElse("").length() >= 5, "expected length >= 5");
    }

}
