// This file is auto-generated by alef. DO NOT EDIT.
package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.Kreuzberg;

/** E2e tests for category: mime_utilities. */
class MimeUtilitiesTest {
    @Test
    void testMimeDetectBytes() throws Exception {
        // Detect MIME type from file bytes
        var result = Kreuzberg.extractFile("");
        assertTrue(result.result().contains("pdf"), "expected to contain: " + "pdf");
    }

    @Test
    void testMimeDetectPath() throws Exception {
        // Detect MIME type from file path
        var result = Kreuzberg.extractFile("");
        assertTrue(result.result().contains("text"), "expected to contain: " + "text");
    }

    @Test
    void testMimeGetExtensions() throws Exception {
        // Get file extensions for a MIME type
        var result = Kreuzberg.extractFile("");
        assertTrue(result.result().contains("pdf"), "expected to contain: " + "pdf");
    }

}
