// This file is auto-generated by alef. DO NOT EDIT.
package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.Kreuzberg;

/** E2e tests for category: render. */
class RenderTest {
    @Test
    void testRenderCustomDpi() throws Exception {
        // Render PDF page with custom DPI
        var result = Kreuzberg.extractFile("");
        // TODO: unsupported assertion type: is_true
        assertTrue(result.byteLength() >= 50, "expected >= 50");
    }

    @Test
    void testRenderIterator() throws Exception {
        // Iterate all PDF pages as PNG images
        var result = Kreuzberg.extractFile("");
        // TODO: unsupported assertion type: is_true
        assertTrue(result.pageCount() >= 1, "expected >= 1");
    }

    @Test
    void testRenderSinglePage() throws Exception {
        // Render a single PDF page to PNG
        var result = Kreuzberg.extractFile("");
        // TODO: unsupported assertion type: is_true
        assertTrue(result.byteLength() >= 100, "expected >= 100");
    }

}
