# This file is auto-generated by alef. DO NOT EDIT.
defmodule Kreuzberg.LayoutRegion do
  @moduledoc "A detected layout region on a page."

  defstruct class: "",
            confidence: 0.0,
            bounding_box: "",
            area_fraction: 0.0
end
