# This file is auto-generated by alef. DO NOT EDIT.
defmodule Kreuzberg.MergedChunk do
  @moduledoc "A merged chunk produced by [`merge_segments`]."

  defstruct text: "",
            byte_start: 0,
            byte_end: 0
end
